### ISSUE TITLE
Description of functions in Class

### ISSUE THREAD

**Issue by Benik3** [Serpen/VBS-VSCode#34]
Description of functions/Subs/Property doesn't show in intellisense:  
![obrazek](https://user-images.githubusercontent.com/4532647/95850829-b11e5800-0d51-11eb-8f94-80f72dca35dd.png)

**Comment by Serpen** [comment]
The reason is a bug, because of indention.
If you clear the leading whitespaces it should worked.
Fixed in commit df73484ec3a1c24b35e7a0801ba26855e0f0f6c8, wait for 1.1.0 Release
