### ISSUE TITLE
Custom Include Pattern does not work

### ISSUE THREAD

**Issue by teremok87** [Serpen/VBS-VSCode#52]
I try to use this Include pattern 
[Ii][Nn][Cc][Ll][Uu][Dd][Ee]\s*\(?[\s]*"([^"]+)"[\s]*\)?  
for this
Include "lib.vbs"

have two files in the folder 
main.vbs :

Include "lib.vbs"

Sub Main
	Hura()
End Sub

and 

lib.vbs:

Sub Hura ()
	Dim vHura : vHura = "Hura!!"
End Sub

Peek and Go to Definition  does not work for Hura() in the file main.vbs 

When i add this folder as Custom Include Dir, then it works fine. But i want only use this setting for libraries directory

By the way with the default Include Pattern it does not work as well

**Comment by Serpen** [comment]
The include search path per default is only the workspace root folder not the folder where the used file is.

So '.' means {workspaceRootFolder} this is a little unclear in my definition.

If you put your lib file in the workspace root it will work?

I will investigate if i can change this behaviour, but i think there was a strange problem with that.

**Comment by teremok87** [comment]
This was my mistake, I did't noticed, that "." is converterted to any path. I replace from the beginning this "." by my own libraries path. That was the reason  becouse it does not worked for local libs anymore.
"." is back and now it works like i expect.

Thank you very mach for your reply an for the plugin. It is very very usefull. Well Done! 
Und Servus aus Bayern :)

**Comment by Serpen** [comment]
Dann kann ich ja auf deutsch schreiben ^^
Trotzdem lasse ich den Bug mal offen und werde in der nächsten Version was fixen.

'.' wird aktuelle Verzeichnis werden und
'${workspaceFolder}' wird das arbeitsmappen root werden

moin aus schleswig-holstein
