### ISSUE TITLE
Some feature Requests  from Bayern

### ISSUE THREAD

**Issue by teremok87** [Serpen/VBS-VSCode#53]
I have to use some costomised vbs language.

1) In this language i need a couple of new extentions.

vbs - normal script file
vbsl - global library file
vbsll - local library file
vbsth - thread file 
vbsm - modul file

If i could just add this new extentions in your setting of the plugin  it would be great.

2) This language was also extenden by a lot of new objects und methods which i would have also colored like a standard vbs methods and objects. 

If i could just add this new methods und objects in your setting of the plugin  it would be great. This new methods would have the same color like the standard vbs methods

3) It would be also  great if my own functions would get also a color when i call them. the colour could be diferen from the standard vbs methods. It would make the code reading way easier.

If i could just add this own methods und objects in your setting of the plugin  it would be great.

P.S: Ich habe auf englisch geschrieben , weil ich dachte, dass die anderen das auch verstehen wollen.
Vielen Dank im Voraus und Servus aus Bayern!

**Comment by Serpen** [comment]
to 1: its a standard feature of vscode, I found no good gui link (but simply click on language in the status bar and select "file association for ???"/"Dateizuordnung für .vbsl konfigurieren")  https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language
_The vbs extension is currently only designed to support pure vbs; asp and event wsl aren't supported._

to 2/3: my extension allows you to add vbs source files as include source via settimg "VBS: Includes". You have to add a file like
```
class myGreatExtension
   public function MyAdvancedFunction(param1, param2)
   end function
end class
```
To support those files is the main reason why i invented the extension.
But it won't support own language features like `var myVar as String`, for those you have to write your own language extension.

![grafik](https://user-images.githubusercontent.com/9609229/120285975-15c8fb80-c2be-11eb-91fd-a6373d21e1f7.png)

to 3: Use see from where a function is included, no different coloring, that again would require your own extension
